# 数据源配置
# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/celestial_db
#     username: utyuu
#     password: 2prayers4lost
#     driver-class-name: com.mysql.cj.jdbc.Driver

# 暂时禁用数据库连接
spring:
  autoconfigure:
      exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# mybatis:
#   mapper-locations: classpath:mapper/*.xml

# 应用程序端口配置
server:
  port: 8080
  